=== blaec/masterjava_3/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="description"/>
                <xs:element ref="Group" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Group">
        <xs:complexType>
            <xs:attribute type="xs:ID" name="name" use="required"/>
            <xs:attribute type="groupStatus" name="type"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="groupStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element type="cityType" name="City"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="User">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="emailType" name="email" use="required"/>
                    <xs:attribute type="flagType" name="flag" use="required"/>
                    <xs:attribute type="xs:IDREF" name="city" use="required"/>
                    <xs:attribute type="xs:IDREFS" name="groups" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== blaec/masterjava_3/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Projects>
        <Project name="topjava">
            <description>topjava project description</description>
            <Group type="FINISHED" name="topjava01"/>
            <Group type="CURRENT" name="topjava02"/>
            <Group type="REGISTERING" name="topjava03"/>
        </Project>
        <Project name="masterjava">
            <description>masterjava project description</description>
            <Group type="CURRENT" name="masterjava01"/>
            <Group type="REGISTERING" name="masterjava02"/>
        </Project>
    </Projects>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Users>
        <User flag="active" city="kiv" email="gmail@gmail.com" groups="topjava01 topjava02">Full Name</User>
        <User flag="superuser" city="spb" email="admin@javaops.ru" groups="topjava03 masterjava02">Admin</User>
        <User flag="deleted" city="spb" email="mail@yandex.ru" groups="topjava02">Deleted</User>
    </Users>
</Payload>
